from pydantic import BaseModel, Field

class HousePriceInputData(BaseModel):
    """Data model for house price prediction input."""
    LotFrontage: float
    LotArea: int
    OverallQual: int
    OverallCond: int
    YearBuilt: int
    YearRemodAdd: int
    MasVnrArea: float
    BsmtFinSF1: int
    BsmtFinSF2: int
    BsmtUnfSF: int
    TotalBsmtSF: int
    FirstFlrSF: int = Field(alias='1stFlrSF')
    SecondFlrSF: int = Field(alias='2ndFlrSF')
    LowQualFinSF: int
    GrLivArea: int
    BsmtFullBath: int
    BsmtHalfBath: int
    FullBath: int
    HalfBath: int
    BedroomAbvGr: int
    KitchenAbvGr: int
    TotRmsAbvGrd: int
    Fireplaces: int
    GarageYrBlt: float
    GarageCars: int
    GarageArea: int
    WoodDeckSF: int
    OpenPorchSF: int
    EnclosedPorch: int
    ThreeSsnPorch: int = Field(alias='3SsnPorch')
    ScreenPorch: int
    PoolArea: int
    MiscVal: int
    MoSold: int
    YrSold: int
    MSZoning_encoded: int
    Street_encoded: int
    Alley_encoded: int
    LotShape_encoded: int
    LandContour_encoded: int
    Utilities_encoded: int
    LotConfig_encoded: int
    LandSlope_encoded: int
    Neighborhood_encoded: int
    Condition1_encoded: int
    Condition2_encoded: int
    BldgType_encoded: int
    HouseStyle_encoded: int
    RoofStyle_encoded: int
    RoofMatl_encoded: int
    Exterior1st_encoded: int
    Exterior2nd_encoded: int
    MasVnrType_encoded: int
    ExterQual_encoded: int
    ExterCond_encoded: int
    Foundation_encoded: int
    BsmtQual_encoded: int
    BsmtCond_encoded: int
    BsmtExposure_encoded: int
    BsmtFinType1_encoded: int
    BsmtFinType2_encoded: int
    Heating_encoded: int
    HeatingQC_encoded: int
    CentralAir_encoded: int
    Electrical_encoded: int
    KitchenQual_encoded: int
    Functional_encoded: int
    FireplaceQu_encoded: int
    GarageType_encoded: int
    GarageFinish_encoded: int
    GarageQual_encoded: int
    GarageCond_encoded: int
    PavedDrive_encoded: int
    PoolQC_encoded: int
    Fence_encoded: int
    MiscFeature_encoded: int
    SaleType_encoded: int
    SaleCondition_encoded: int
    MSSubClass_encoded: int
    Age: int
    RemodAge: int
    HasGarage: int
    HasBasement: int
    UnfBsmtPercent: float
    LivLotRatio: float
    AreaPerRoom: float

class HousePriceOutputData(BaseModel):
    """Data model for house price prediction output."""
    SalePrice: float


dummy_input = {
                "LotFrontage": 65.0, 
                "LotArea": 8450, 
                "OverallQual": 7, 
                "OverallCond": 5, 
                "YearBuilt": 2003,
                "YearRemodAdd": 2003, 
                "MasVnrArea": 196.0, 
                "BsmtFinSF1": 706, 
                "BsmtFinSF2": 0, 
                "BsmtUnfSF": 150,
                "TotalBsmtSF": 856, 
                "1stFlrSF": 856, 
                "2ndFlrSF": 854, 
                "LowQualFinSF": 0, 
                "GrLivArea": 1710,
                "BsmtFullBath": 1, 
                "BsmtHalfBath": 0, 
                "FullBath": 2, 
                "HalfBath": 1, 
                "BedroomAbvGr": 3,
                "KitchenAbvGr": 1, 
                "TotRmsAbvGrd": 8, 
                "Fireplaces": 0, 
                "GarageYrBlt": 2003.0, 
                "GarageCars": 2,
                "GarageArea": 548, 
                "WoodDeckSF": 0, 
                "OpenPorchSF": 61, 
                "EnclosedPorch": 0, 
                "3SsnPorch": 0,
                "ScreenPorch": 0, 
                "PoolArea": 0, 
                "MiscVal": 0, 
                "MoSold": 2, 
                "YrSold": 2008, 
                "MSZoning_encoded": 3,
                "Street_encoded": 1, 
                "Alley_encoded": 1, 
                "LotShape_encoded": 3, 
                "LandContour_encoded": 3,
                "Utilities_encoded": 0, 
                "LotConfig_encoded": 4, 
                "LandSlope_encoded": 0, 
                "Neighborhood_encoded": 5,
                "Condition1_encoded": 2, 
                "Condition2_encoded": 2, 
                "BldgType_encoded": 0, 
                "HouseStyle_encoded": 5,
                "RoofStyle_encoded": 1, 
                "RoofMatl_encoded": 1, 
                "Exterior1st_encoded": 12, 
                "Exterior2nd_encoded": 13,
                "MasVnrType_encoded": 1, 
                "ExterQual_encoded": 2, 
                "ExterCond_encoded": 4, 
                "Foundation_encoded": 2,
                "BsmtQual_encoded": 2, 
                "BsmtCond_encoded": 3, 
                "BsmtExposure_encoded": 3, 
                "BsmtFinType1_encoded": 2,
                "BsmtFinType2_encoded": 5, 
                "Heating_encoded": 1, 
                "HeatingQC_encoded": 0, 
                "CentralAir_encoded": 1,
                "Electrical_encoded": 4, 
                "KitchenQual_encoded": 2, 
                "Functional_encoded": 6, 
                "FireplaceQu_encoded": 5,
                "GarageType_encoded": 1, 
                "GarageFinish_encoded": 1, 
                "GarageQual_encoded": 4, 
                "GarageCond_encoded": 4,
                "PavedDrive_encoded": 2, 
                "PoolQC_encoded": 3, 
                "Fence_encoded": 4, 
                "MiscFeature_encoded": 4,
                "SaleType_encoded": 8, 
                "SaleCondition_encoded": 4, 
                "MSSubClass_encoded": 5, 
                "Age": 5, "RemodAge": 5,
                "HasGarage": 1, 
                "HasBasement": 1, 
                "UnfBsmtPercent": 0.17523364485981308,
                "LivLotRatio": 0.20236686390532544, 
                "AreaPerRoom": 213.75
            }

